apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amazonq-config-pvc
  namespace: ai-agents
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: shared-workspace
